#!/bin/bash
# This script is ran from the docker container running flask.
# Called in /dashboard/flask/app/api/resources.Stop:post
# SOURCE_IPS is defined in dashboard.env, available in the flask container

( IFS=:
	for NODE in $SOURCE_IPS; do
	  # On each source machine, kill hping3 activities
		ssh -o StrictHostKeyChecking=no admin@$NODE "kill -9 \$(ps -e | grep hping3 | grep -v grep | awk '{print \$1}')"
	done
)

